export const COUNTRIES = [
    { code: 'AF', name: 'Afghanistan', lifeExpectancy: 62.9 },
    { code: 'AL', name: 'Albania', lifeExpectancy: 76.5 },
    { code: 'DZ', name: 'Algeria', lifeExpectancy: 77.1 },
    { code: 'AO', name: 'Angola', lifeExpectancy: 61.6 },
    { code: 'AR', name: 'Argentina', lifeExpectancy: 75.4 },
    { code: 'AM', name: 'Armenia', lifeExpectancy: 72.0 },
    { code: 'AU', name: 'Australia', lifeExpectancy: 83.3 },
    { code: 'AT', name: 'Austria', lifeExpectancy: 81.6 },
    { code: 'AZ', name: 'Azerbaijan', lifeExpectancy: 69.4 },
    { code: 'BD', name: 'Bangladesh', lifeExpectancy: 72.4 },
    { code: 'BE', name: 'Belgium', lifeExpectancy: 81.9 },
    { code: 'BR', name: 'Brazil', lifeExpectancy: 72.8 },
    { code: 'CA', name: 'Canada', lifeExpectancy: 82.6 },
    { code: 'CN', name: 'China', lifeExpectancy: 78.2 },
    { code: 'CO', name: 'Colombia', lifeExpectancy: 72.8 },
    { code: 'DK', name: 'Denmark', lifeExpectancy: 81.4 },
    { code: 'EG', name: 'Egypt', lifeExpectancy: 70.2 },
    { code: 'FI', name: 'Finland', lifeExpectancy: 82.0 },
    { code: 'FR', name: 'France', lifeExpectancy: 82.5 },
    { code: 'DE', name: 'Germany', lifeExpectancy: 80.9 },
    { code: 'GR', name: 'Greece', lifeExpectancy: 80.1 },
    { code: 'IN', name: 'India', lifeExpectancy: 70.8 }, // Updated roughly
    { code: 'ID', name: 'Indonesia', lifeExpectancy: 67.6 },
    { code: 'IR', name: 'Iran', lifeExpectancy: 73.9 },
    { code: 'IQ', name: 'Iraq', lifeExpectancy: 70.4 },
    { code: 'IE', name: 'Ireland', lifeExpectancy: 82.1 },
    { code: 'IL', name: 'Israel', lifeExpectancy: 82.6 },
    { code: 'IT', name: 'Italy', lifeExpectancy: 82.7 },
    { code: 'JP', name: 'Japan', lifeExpectancy: 84.5 },
    { code: 'MX', name: 'Mexico', lifeExpectancy: 70.2 },
    { code: 'NL', name: 'Netherlands', lifeExpectancy: 81.7 },
    { code: 'NZ', name: 'New Zealand', lifeExpectancy: 82.5 },
    { code: 'NG', name: 'Nigeria', lifeExpectancy: 52.7 },
    { code: 'NO', name: 'Norway', lifeExpectancy: 83.2 },
    { code: 'PK', name: 'Pakistan', lifeExpectancy: 66.1 },
    { code: 'PH', name: 'Philippines', lifeExpectancy: 69.3 },
    { code: 'PL', name: 'Poland', lifeExpectancy: 75.6 },
    { code: 'PT', name: 'Portugal', lifeExpectancy: 81.0 },
    { code: 'RU', name: 'Russia', lifeExpectancy: 69.4 },
    { code: 'SA', name: 'Saudi Arabia', lifeExpectancy: 76.9 },
    { code: 'SG', name: 'Singapore', lifeExpectancy: 83.1 },
    { code: 'ZA', name: 'South Africa', lifeExpectancy: 62.3 },
    { code: 'KR', name: 'South Korea', lifeExpectancy: 83.6 }, // Republic of Korea
    { code: 'ES', name: 'Spain', lifeExpectancy: 83.3 },
    { code: 'LK', name: 'Sri Lanka', lifeExpectancy: 76.4 },
    { code: 'SE', name: 'Sweden', lifeExpectancy: 83.0 },
    { code: 'CH', name: 'Switzerland', lifeExpectancy: 83.8 },
    { code: 'TR', name: 'Turkey', lifeExpectancy: 78.6 },
    { code: 'UA', name: 'Ukraine', lifeExpectancy: 68.6 },
    { code: 'AE', name: 'United Arab Emirates', lifeExpectancy: 79.2 },
    { code: 'GB', name: 'United Kingdom', lifeExpectancy: 80.7 },
    { code: 'US', name: 'United States', lifeExpectancy: 76.3 },
    { code: 'VN', name: 'Vietnam', lifeExpectancy: 73.6 },
].sort((a, b) => a.name.localeCompare(b.name));
